# Generated by Django 5.2.4 on 2025-08-20 15:26

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Rejected')], default=1)),
                ('violation_type', models.IntegerField(blank=True, choices=[(1, 'Jailbreak'), (2, 'Harmful Content'), (3, 'Abuse')], null=True)),
                ('reason', models.TextField(max_length=2000)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='chatbot.message')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SafetyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('event_type', models.IntegerField(choices=[(1, 'Query Blocked'), (2, 'Policy Violation'), (3, 'Suspicious Pattern')])),
                ('compliance_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_events', to='chatbot.compliancecheck')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
